version: "3"

services:

  strapi:
    container_name: sv08ludweiler-strapi
    build:
      context: .
      dockerfile: Dockerfile.server.prod
      target: strapi
    image: sv08ludweiler-strapi
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./cms/config:/opt/app/config
      - ./cms/src:/opt/app/src
      - ./cms/package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./cms/.env.dev:/opt/app/.env
      - ./cms/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"
    networks:
      - ludweiler
    depends_on:
      - strapiDB

  strapiDB:
    container_name: sv08ludweiler-strapiDB
    restart: unless-stopped
    image: postgres:15-alpine
    volumes:
      # using dev volume
      - strapi-data:/var/lib/postgresql/data/
      # using a volume
      # - sv08ludweiler-strapi-data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - ludweiler

  sveltekit-node:
    container_name: sv08ludweiler-sveltekit-node
    image: sv08ludweiler-sveltekit-node
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    environment:
      # overwrite 1337 in env file
      - PORT=3000
    ports:
      - 1338:3000
    depends_on:
      - strapi
    networks:
      - ludweiler    
    build:
      context: .
      dockerfile: Dockerfile.server.prod
      target: sveltekit-node
      args:
        - NODE_ENV=${NODE_ENV}
        - STRAPI_HOST=${STRAPI_HOST}
        - PUBLIC_STRAPI_HOST=${PUBLIC_STRAPI_HOST}
        - STRAPI_API_TOKEN=${STRAPI_API_TOKEN}

  # sveltekit:
  #   container_name: sv08ludweiler-sveltekit
  #   image: sv08ludweiler-sveltekit
  #   restart: unless-stopped
  #   tty: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server.prod
  #     target: sveltekit
  #   user: "node"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./node_modules:/opt/node_modules
  #     - ./frontend/build-static:/opt/build-static
  #   networks:
  #     - ludweiler
  #   depends_on:
  #     - strapi

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - ludweiler

volumes:
  sv08ludweiler-sveltekit-data:
  strapi-data:


networks:
  ludweiler:
    name: ludweiler
    driver: bridge
