version: "3"

services:

  strapi:
    container_name: sv08ludweiler-strapi
    build:
      context: .
      dockerfile: Dockerfile.server.prod
      target: strapi
      args:
        - STRAPI_HOST=0.0.0.0
        - STRAPI_PORT=1337
    image: sv08ludweiler-strapi
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      # /var/customers/docker/ludweiler
      - sv08ludweiler-strapi-public:/opt/app/public
      - ./bridge:/opt/app/bridge
    ports:
      - "1337:1337"
    networks:
      - ludweiler
    depends_on:
      - strapiDB

  strapiDB:
    container_name: sv08ludweiler-strapiDB
    restart: unless-stopped
    image: postgres:15-alpine
    env_file:
      - .env.prod
    volumes:
      # - strapi-data:/var/lib/postgresql/data/ #using dev volume
      # using a volume
      - sv08ludweiler-strapi-database:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    networks:
      - ludweiler

  sveltekit-node:
    container_name: sv08ludweiler-sveltekit-node
    image: sv08ludweiler-sveltekit-node
    restart: unless-stopped
    tty: true
    env_file:
      - .env.prod
    ports:
      - 1338:3000
    depends_on:
      - strapi
    networks:
      - ludweiler
    build:
      context: .
      dockerfile: Dockerfile.server.prod
      target: sveltekit-node
      args:
        - NODE_ENV=${NODE_ENV}
        - FRONTEND_STRAPI_HOST=${FRONTEND_STRAPI_HOST}
        - PUBLIC_FRONTEND_STRAPI_HOST=${PUBLIC_FRONTEND_STRAPI_HOST}
        - STRAPI_API_TOKEN=${STRAPI_API_TOKEN}

  # sveltekit:
  #   container_name: sv08ludweiler-sveltekit
  #   image: sv08ludweiler-sveltekit
  #   restart: unless-stopped
  #   tty: true
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.server.prod
  #     target: sveltekit
  #   user: "node"
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./node_modules:/opt/node_modules
  #     - ./frontend/build-static:/opt/build-static
  #   networks:
  #     - ludweiler
  #   depends_on:
  #     - strapi

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - ludweiler

volumes:
  sv08ludweiler-sveltekit-data:
  sv08ludweiler-strapi-public:
  sv08ludweiler-strapi-database:


networks:
  ludweiler:
    name: ludweiler
    driver: bridge
